/**
 * 
 */
package org.eclipsescout.egt.shared.graph;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EgtGraphTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public EgtGraphTablePageData() {
  }

  @Override
  public EgtGraphTableRowData addRow() {
    return (EgtGraphTableRowData) super.addRow();
  }

  @Override
  public EgtGraphTableRowData addRow(int rowState) {
    return (EgtGraphTableRowData) super.addRow(rowState);
  }

  @Override
  public EgtGraphTableRowData createRow() {
    return new EgtGraphTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return EgtGraphTableRowData.class;
  }

  @Override
  public EgtGraphTableRowData[] getRows() {
    return (EgtGraphTableRowData[]) super.getRows();
  }

  @Override
  public EgtGraphTableRowData rowAt(int index) {
    return (EgtGraphTableRowData) super.rowAt(index);
  }

  public void setRows(EgtGraphTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class EgtGraphTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String graphNr = "graphNr";
    public static final String graphName = "graphName";
    private Long m_graphNr;
    private String m_graphName;

    public EgtGraphTableRowData() {
    }

    /**
     * @return the GraphNr
     */
    public Long getGraphNr() {
      return m_graphNr;
    }

    /**
     * @param graphNr
     *          the GraphNr to set
     */
    public void setGraphNr(Long graphNr) {
      m_graphNr = graphNr;
    }

    /**
     * @return the GraphName
     */
    public String getGraphName() {
      return m_graphName;
    }

    /**
     * @param graphName
     *          the GraphName to set
     */
    public void setGraphName(String graphName) {
      m_graphName = graphName;
    }
  }
}
