/**
 * 
 */
package org.eclipsescout.egt.shared.graph;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EgtGraphFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public EgtGraphFormData() {
  }

  public GraphName getGraphName() {
    return getFieldByClass(GraphName.class);
  }

  /**
   * access method for property GraphNr.
   */
  public Long getGraphNr() {
    return getGraphNrProperty().getValue();
  }

  /**
   * access method for property GraphNr.
   */
  public void setGraphNr(Long graphNr) {
    getGraphNrProperty().setValue(graphNr);
  }

  public GraphNrProperty getGraphNrProperty() {
    return getPropertyByClass(GraphNrProperty.class);
  }

  /**
   * access method for property SvgText.
   */
  public String getSvgText() {
    return getSvgTextProperty().getValue();
  }

  /**
   * access method for property SvgText.
   */
  public void setSvgText(String svgText) {
    getSvgTextProperty().setValue(svgText);
  }

  public SvgTextProperty getSvgTextProperty() {
    return getPropertyByClass(SvgTextProperty.class);
  }

  public static class GraphName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public GraphName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class GraphNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;

    public GraphNrProperty() {
    }
  }

  public static class SvgTextProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public SvgTextProperty() {
    }
  }
}
