/**
 * 
 */
package org.eclipsescout.egt.shared.graph;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class GraphSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public GraphSearchFormData() {
  }

  public GraphName getGraphName() {
    return getFieldByClass(GraphName.class);
  }

  public static class GraphName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public GraphName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
