package org.eclipse.scout.apps.egt.shared.graph;

import javax.annotation.Generated;

import org.eclipse.scout.apps.egt.shared.graph.EgtGraphStorage.GraphInformation;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.eclipse.scout.apps.egt.client.graph.EgtGraphTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EgtGraphTablePageData extends AbstractTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public EgtGraphTableRowData addRow() {
		return (EgtGraphTableRowData) super.addRow();
	}

	@Override
	public EgtGraphTableRowData addRow(int rowState) {
		return (EgtGraphTableRowData) super.addRow(rowState);
	}

	@Override
	public EgtGraphTableRowData createRow() {
		return new EgtGraphTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return EgtGraphTableRowData.class;
	}

	@Override
	public EgtGraphTableRowData[] getRows() {
		return (EgtGraphTableRowData[]) super.getRows();
	}

	@Override
	public EgtGraphTableRowData rowAt(int index) {
		return (EgtGraphTableRowData) super.rowAt(index);
	}

	public void setRows(EgtGraphTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class EgtGraphTableRowData extends AbstractTableRowData {

		private static final long serialVersionUID = 1L;
		public static final String graphInformation = "graphInformation";
		public static final String graphName = "graphName";
		private GraphInformation m_graphInformation;
		private String m_graphName;

		public GraphInformation getGraphInformation() {
			return m_graphInformation;
		}

		public void setGraphInformation(GraphInformation newGraphInformation) {
			m_graphInformation = newGraphInformation;
		}

		public String getGraphName() {
			return m_graphName;
		}

		public void setGraphName(String newGraphName) {
			m_graphName = newGraphName;
		}
	}
}
