package org.eclipse.scout.apps.egt.shared.graph;

import javax.annotation.Generated;

import org.eclipse.scout.apps.egt.shared.graph.EgtGraphStorage.GraphInformation;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "org.eclipse.scout.apps.egt.client.graph.EgtGraphForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EgtGraphFormData extends AbstractFormData {

	private static final long serialVersionUID = 1L;

	/**
	 * access method for property GraphInformation.
	 */
	public GraphInformation getGraphInformation() {
		return getGraphInformationProperty().getValue();
	}

	/**
	 * access method for property GraphInformation.
	 */
	public void setGraphInformation(GraphInformation graphInformation) {
		getGraphInformationProperty().setValue(graphInformation);
	}

	public GraphInformationProperty getGraphInformationProperty() {
		return getPropertyByClass(GraphInformationProperty.class);
	}

	public GraphName getGraphName() {
		return getFieldByClass(GraphName.class);
	}

	/**
	 * access method for property SvgText.
	 */
	public String getSvgText() {
		return getSvgTextProperty().getValue();
	}

	/**
	 * access method for property SvgText.
	 */
	public void setSvgText(String svgText) {
		getSvgTextProperty().setValue(svgText);
	}

	public SvgTextProperty getSvgTextProperty() {
		return getPropertyByClass(SvgTextProperty.class);
	}

	public static class GraphInformationProperty extends AbstractPropertyData<GraphInformation> {

		private static final long serialVersionUID = 1L;
	}

	public static class GraphName extends AbstractValueFieldData<String> {

		private static final long serialVersionUID = 1L;
	}

	public static class SvgTextProperty extends AbstractPropertyData<String> {

		private static final long serialVersionUID = 1L;
	}
}
