/**
 * 
 */
package org.eclipsescout.egt.shared.configuration;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.pagedata.PageDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EgtConfigurationTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  public EgtConfigurationTablePageData() {
  }

  @Override
  public EgtConfigurationTableRowData addRow() {
    return (EgtConfigurationTableRowData) super.addRow();
  }

  @Override
  public EgtConfigurationTableRowData addRow(int rowState) {
    return (EgtConfigurationTableRowData) super.addRow(rowState);
  }

  @Override
  public EgtConfigurationTableRowData createRow() {
    return new EgtConfigurationTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return EgtConfigurationTableRowData.class;
  }

  @Override
  public EgtConfigurationTableRowData[] getRows() {
    return (EgtConfigurationTableRowData[]) super.getRows();
  }

  @Override
  public EgtConfigurationTableRowData rowAt(int index) {
    return (EgtConfigurationTableRowData) super.rowAt(index);
  }

  public void setRows(EgtConfigurationTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class EgtConfigurationTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String parameter = "parameter";
    public static final String parameterName = "parameterName";
    public static final String parameterValue = "parameterValue";
    private AbstractParameter m_parameter;
    private String m_parameterName;
    private String m_parameterValue;

    public EgtConfigurationTableRowData() {
    }

    /**
     * @return the Parameter
     */
    public AbstractParameter getParameter() {
      return m_parameter;
    }

    /**
     * @param parameter
     *          the Parameter to set
     */
    public void setParameter(AbstractParameter parameter) {
      m_parameter = parameter;
    }

    /**
     * @return the ParameterName
     */
    public String getParameterName() {
      return m_parameterName;
    }

    /**
     * @param parameterName
     *          the ParameterName to set
     */
    public void setParameterName(String parameterName) {
      m_parameterName = parameterName;
    }

    /**
     * @return the ParameterValue
     */
    public String getParameterValue() {
      return m_parameterValue;
    }

    /**
     * @param parameterValue
     *          the ParameterValue to set
     */
    public void setParameterValue(String parameterValue) {
      m_parameterValue = parameterValue;
    }
  }
}
